In [1]:
# Import Dependencies
import pandas as pd

In [2]:
# Reference the file where the CSV is located
crime_csv_path = "/Users/nmeyer/Desktop/Bootcamp/M4 - Pandas/Week 4 - Class 2/Activities/PortlandCrime/crime_incident_data2017.csv"

# Import the data into a Pandas DataFrame
crime_df = pd.read_csv(crime_csv_path)
crime_df

,Address,Case Number,Crime Against,Neighborhood,Number of Records,Occur Date,Occur Month Year,Occur Time,Offense Category,Offense Count,Offense Type,Open Data Lat,Open Data Lon,Open Data X,Open Data Y,Report Date,Report Month Year
0,NaN,17-X4762181,Person,NaN,1,1/1/96,1/1/96,800,Sex Offenses,1,Rape,NaN,NaN,NaN,NaN,1/26/17,1/1/17
1,NaN,17-X4757824,Property,Centennial,1,1/20/00,1/1/00,1615,Fraud Offenses,1,Identity Theft,NaN,NaN,NaN,NaN,1/20/17,1/1/17
2,200 BLOCK OF SE 78TH AVE,17-900367,Property,Montavilla,1,12/1/03,12/1/03,800,Fraud Offenses,1,False Pretenses/Swindle/Confidence Game,45.5207,-122.583,7668150.0,682825.0,1/9/17,1/1/17
3,NaN,17-X4748982,Property,Southwest Hills,1,1/1/10,1/1/10,0,Fraud Offenses,1,Identity Theft,NaN,NaN,NaN,NaN,1/5/17,1/1/17
4,NaN,17-X4748982,Property,Southwest Hills,1,1/1/10,1/1/10,0,Larceny Offenses,1,All Other Larceny,NaN,NaN,NaN,NaN,1/5/17,1/1/17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40891,6200 BLOCK OF SE ALDER ST,17-912799,Property,Mt Tabor,1,8/30/17,8/1/17,1445,Fraud Offenses,1,Identity Theft,45.5177,-122.600,7663895.0,681833.0,8/31/17,8/1/17
40892,600 BLOCK OF W BURNSIDE ST,17-912792,Property,Downtown,1,8/30/17,8/1/17,2230,Larceny Offenses,1,All Other Larceny,45.5230,-122.677,7644223.0,684292.0,8/31/17,8/1/17
40893,7500 BLOCK OF N INTERSTATE AVE,17-285542,Property,Kenton,1,8/30/17,8/1/17,2230,Larceny Offenses,1,All Other Larceny,45.5775,-122.682,7643486.0,704201.0,8/31/17,8/1/17
40894,9200 BLOCK OF N PENINSULAR AVE,17-285752,Property,Kenton,1,8/30/17,8/1/17,1800,Larceny Offenses,1,All Other Larceny,45.5895,-122.697,7639724.0,708648.0,8/31/17,8/1/17
40895,E BURNSIDE ST / NE COUCH ST,17-912795,Property,Kerns,1,8/30/17,8/1/17,2210,Larceny Offenses,1,A,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# look for missing values
crime_df.count()

Address              37245
Case Number          40896
Crime Against        40896
Neighborhood         39582
Number of Records    40896
Occur Date           40896
Occur Month Year     40896
Occur Time           40896
Offense Category     40896
Offense Count        40896
Offense Type         40896
Open Data Lat        36593
Open Data Lon        36593
Open Data X          36593
Open Data Y          36593
Report Date          40895
Report Month Year    40895
dtype: int64

In [4]:
# drop null rows
no_null_crime_df = crime_df.dropna(how='any')

In [5]:
# verify counts
no_null_crime_df.count()

Address              36030
Case Number          36030
Crime Against        36030
Neighborhood         36030
Number of Records    36030
Occur Date           36030
Occur Month Year     36030
Occur Time           36030
Offense Category     36030
Offense Count        36030
Offense Type         36030
Open Data Lat        36030
Open Data Lon        36030
Open Data X          36030
Open Data Y          36030
Report Date          36030
Report Month Year    36030
dtype: int64

In [6]:
# Check to see if there are any values with mispelled or similar values in "Offense Type"
no_null_crime_df["Offense Type"].value_counts()

Theft From Motor Vehicle                       6925
Motor Vehicle Theft                            4669
All Other Larceny                              4550
Vandalism                                      3842
Burglary                                       2813
Shoplifting                                    2255
Identity Theft                                 1791
Simple Assault                                 1213
Drug/Narcotic Violations                       1090
Theft of Motor Vehicle Parts or Accessories    1070
Intimidation                                    898
Theft From Building                             893
False Pretenses/Swindle/Confidence Game         869
Aggravated Assault                              834
Robbery                                         606
Counterfeiting/Forgery                          448
Weapons Law Violations                          265
Credit Card/ATM Fraud                           226
Arson                                           200
Prostitution                                    143
Pocket-Picking                                   94
Purse-Snatching                                  89
Embezzlement                                     72
Stolen Property Offenses                         57
Kidnapping/Abduction                             22
Theft From Coin-Operated Machine or Device       20
Hacking/Computer Invasion                        19
Animal Cruelty                                   17
Pornography/Obscene Material                     10
Extortion/Blackmail                               8
Assisting or Promoting Prostitution               7
Drug Equipment Violations                         6
Impersonation                                     4
Wire Fraud                                        3
Commercial Sex Acts                               1
Welfare Fraud                                     1
Name: Offense Type, dtype: int64

In [7]:
# Combining similar offenses together
no_null_crime_df = no_null_crime_df.replace(
    {"Commercial Sex Acts": "Prostitution", "Assisting or Promoting Prostitution": "Prostitution"})
no_null_crime_df

,Address,Case Number,Crime Against,Neighborhood,Number of Records,Occur Date,Occur Month Year,Occur Time,Offense Category,Offense Count,Offense Type,Open Data Lat,Open Data Lon,Open Data X,Open Data Y,Report Date,Report Month Year
2,200 BLOCK OF SE 78TH AVE,17-900367,Property,Montavilla,1,12/1/03,12/1/03,800,Fraud Offenses,1,False Pretenses/Swindle/Confidence Game,45.5207,-122.583,7668150.0,682825.0,1/9/17,1/1/17
5,5400 BLOCK OF NE MALLORY AVE,17-900129,Property,King,1,11/28/10,11/1/10,1612,Fraud Offenses,1,Identity Theft,45.5625,-122.664,7647987.0,698581.0,1/3/17,1/1/17
6,5000 BLOCK OF NE 19TH AVE,17-901079,Property,Vernon,1,11/8/13,11/1/13,1200,Fraud Offenses,1,False Pretenses/Swindle/Confidence Game,45.5594,-122.646,7652567.0,697337.0,1/26/17,1/1/17
7,5000 BLOCK OF NE 19TH AVE,17-901079,Property,Vernon,1,11/8/13,11/1/13,1200,Fraud Offenses,1,Identity Theft,45.5594,-122.646,7652567.0,697337.0,1/26/17,1/1/17
8,12000 BLOCK OF SE PINE ST,17-900253,Property,Hazelwood,1,1/6/14,1/1/14,805,Fraud Offenses,1,Credit Card/ATM Fraud,45.5204,-122.539,7679522.0,682404.0,1/6/17,1/1/17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40890,1000 BLOCK OF SW JEFFERSON ST,17-286182,Property,Downtown,1,8/30/17,8/1/17,1100,Fraud Offenses,1,Identity Theft,45.5161,-122.685,7642141.0,681831.0,8/31/17,8/1/17
40891,6200 BLOCK OF SE ALDER ST,17-912799,Property,Mt Tabor,1,8/30/17,8/1/17,1445,Fraud Offenses,1,Identity Theft,45.5177,-122.600,7663895.0,681833.0,8/31/17,8/1/17
40892,600 BLOCK OF W BURNSIDE ST,17-912792,Property,Downtown,1,8/30/17,8/1/17,2230,Larceny Offenses,1,All Other Larceny,45.5230,-122.677,7644223.0,684292.0,8/31/17,8/1/17
40893,7500 BLOCK OF N INTERSTATE AVE,17-285542,Property,Kenton,1,8/30/17,8/1/17,2230,Larceny Offenses,1,All Other Larceny,45.5775,-122.682,7643486.0,704201.0,8/31/17,8/1/17
40894,9200 BLOCK OF N PENINSULAR AVE,17-285752,Property,Kenton,1,8/30/17,8/1/17,1800,Larceny Offenses,1,All Other Larceny,45.5895,-122.697,7639724.0,708648.0,8/31/17,8/1/17

In [8]:
# Check to see if you comnbined similar offenses correctly in "Offense Type".
no_null_crime_df["Offense Type"].value_counts()

Theft From Motor Vehicle                       6925
Motor Vehicle Theft                            4669
All Other Larceny                              4550
Vandalism                                      3842
Burglary                                       2813
Shoplifting                                    2255
Identity Theft                                 1791
Simple Assault                                 1213
Drug/Narcotic Violations                       1090
Theft of Motor Vehicle Parts or Accessories    1070
Intimidation                                    898
Theft From Building                             893
False Pretenses/Swindle/Confidence Game         869
Aggravated Assault                              834
Robbery                                         606
Counterfeiting/Forgery                          448
Weapons Law Violations                          265
Credit Card/ATM Fraud                           226
Arson                                           200
Prostitution                                    151
Pocket-Picking                                   94
Purse-Snatching                                  89
Embezzlement                                     72
Stolen Property Offenses                         57
Kidnapping/Abduction                             22
Theft From Coin-Operated Machine or Device       20
Hacking/Computer Invasion                        19
Animal Cruelty                                   17
Pornography/Obscene Material                     10
Extortion/Blackmail                               8
Drug Equipment Violations                         6
Impersonation                                     4
Wire Fraud                                        3
Welfare Fraud                                     1
Name: Offense Type, dtype: int64

In [9]:
# Get the number of crimes against property, society, and person.
no_null_crime_df["Crime Against"].value_counts()

Property    31524
Person       2968
Society      1538
Name: Crime Against, dtype: int64